"""add library_root and photo tables

Revision ID: 824b48087c82
Revises: aac41171b293
Create Date: 2026-07-29 13:05:15.877544

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "824b48087c82"
down_revision: str | Sequence[str] | None = "aac41171b293"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library_root",
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("follow_symlinks", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "photo",
        sa.Column("library_root_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sa.String(), nullable=False),
        sa.Column("relative_path_folded", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("file_mtime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("captured_at_local", sa.DateTime(), nullable=True),
        sa.Column("captured_at_offset_minutes", sa.Integer(), nullable=True),
        sa.Column("captured_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captured_at_source", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_root_id"],
            ["library_root.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "library_root_id", "relative_path_folded", name="uq_photo_root_relpath_folded"
        ),
    )
    op.create_index("ix_photo_content_hash", "photo", ["content_hash"], unique=False)
    op.create_index("ix_photo_status", "photo", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_photo_status", table_name="photo")
    op.drop_index("ix_photo_content_hash", table_name="photo")
    op.drop_table("photo")
    op.drop_table("library_root")
    # ### end Alembic commands ###
