"""add metadata table

Revision ID: c9755b24972d
Revises: 824b48087c82
Create Date: 2026-07-29 16:41:39.910853

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9755b24972d"
down_revision: str | Sequence[str] | None = "824b48087c82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metadata",
        sa.Column("photo_id", sa.Uuid(), nullable=False),
        sa.Column("camera_make", sa.String(), nullable=True),
        sa.Column("camera_model", sa.String(), nullable=True),
        sa.Column("lens", sa.String(), nullable=True),
        sa.Column("focal_length", sa.Float(), nullable=True),
        sa.Column("aperture", sa.Float(), nullable=True),
        sa.Column("shutter_speed", sa.Float(), nullable=True),
        sa.Column("iso", sa.Integer(), nullable=True),
        sa.Column("gps_lat", sa.Float(), nullable=True),
        sa.Column("gps_lon", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("orientation", sa.Integer(), nullable=True),
        sa.Column("raw_exif_blob", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photo.id"],
        ),
        sa.PrimaryKeyConstraint("photo_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metadata")
    # ### end Alembic commands ###
