/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Version */
    get: operations["version_version_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/photos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Photos */
    get: operations["list_photos_api_v1_photos_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/photos/{photo_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Photo Detail */
    get: operations["get_photo_detail_api_v1_photos__photo_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Search */
    post: operations["search_api_v1_search_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/thumbnails/{photo_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Thumbnail */
    get: operations["get_thumbnail_api_v1_thumbnails__photo_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AiResultSummary */
    AiResultSummary: {
      /** Capability */
      capability: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Confidence */
      confidence: number;
      /** Model Version */
      model_version: string;
    };
    /** DateRangeRequest */
    DateRangeRequest: {
      /** Start */
      start?: string | null;
      /** End */
      end?: string | null;
    };
    /** GpsBoundingBoxRequest */
    GpsBoundingBoxRequest: {
      /** Min Lat */
      min_lat: number;
      /** Max Lat */
      max_lat: number;
      /** Min Lon */
      min_lon: number;
      /** Max Lon */
      max_lon: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
    };
    /** MetadataFiltersRequest */
    MetadataFiltersRequest: {
      date_range?: components["schemas"]["DateRangeRequest"] | null;
      /** Camera Model */
      camera_model?: string | null;
      /** Min Rating */
      min_rating?: number | null;
      gps_bbox?: components["schemas"]["GpsBoundingBoxRequest"] | null;
    };
    /** PhotoDetailResponse */
    PhotoDetailResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Relative Path */
      relative_path: string;
      /** Captured At Utc */
      captured_at_utc: string | null;
      /** Camera Make */
      camera_make: string | null;
      /** Camera Model */
      camera_model: string | null;
      /** Width */
      width: number | null;
      /** Height */
      height: number | null;
      /** Ai Results */
      ai_results: components["schemas"]["AiResultSummary"][];
    };
    /** PhotoListResponse */
    PhotoListResponse: {
      /** Items */
      items: components["schemas"]["PhotoSummary"][];
      /** Next Offset */
      next_offset: number | null;
    };
    /** PhotoSummary */
    PhotoSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Relative Path */
      relative_path: string;
      /** Captured At Utc */
      captured_at_utc: string | null;
    };
    /** SearchQueryRequest */
    SearchQueryRequest: {
      /** Text */
      text?: string | null;
      filters?: components["schemas"]["MetadataFiltersRequest"] | null;
      /**
       * Mode
       * @default hybrid
       * @enum {string}
       */
      mode: "metadata" | "text" | "semantic" | "hybrid" | "similar_to";
      /** Reference Photo Id */
      reference_photo_id?: string | null;
      /**
       * Limit
       * @default 100
       */
      limit: number;
      /**
       * Offset
       * @default 0
       */
      offset: number;
    };
    /** SearchResponse */
    SearchResponse: {
      /** Items */
      items: components["schemas"]["SearchResultItem"][];
    };
    /** SearchResultItem */
    SearchResultItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Relative Path */
      relative_path: string;
      /** Captured At Utc */
      captured_at_utc: string | null;
      /** Score */
      score: number;
    };
    /**
     * ThumbSize
     * @enum {string}
     */
    ThumbSize: "grid" | "preview";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VersionResponse */
    VersionResponse: {
      /** Core Api Version */
      core_api_version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  version_version_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_photos_api_v1_photos_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PhotoListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_photo_detail_api_v1_photos__photo_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PhotoDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_api_v1_search_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchQueryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_thumbnail_api_v1_thumbnails__photo_id__get: {
    parameters: {
      query: {
        size: components["schemas"]["ThumbSize"];
        token?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
